// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVideoInQueue(arg1) {
  return window['go']['main']['App']['AddVideoInQueue'](arg1);
}

export function ConnectWSRoom(arg1) {
  return window['go']['main']['App']['ConnectWSRoom'](arg1);
}

export function CreateRoom() {
  return window['go']['main']['App']['CreateRoom']();
}

export function DeleteVideoInQueue(arg1) {
  return window['go']['main']['App']['DeleteVideoInQueue'](arg1);
}

export function GetListVideo(arg1) {
  return window['go']['main']['App']['GetListVideo'](arg1);
}

export function ListenState() {
  return window['go']['main']['App']['ListenState']();
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function PlayAndPause() {
  return window['go']['main']['App']['PlayAndPause']();
}

export function ReturnBaseURL() {
  return window['go']['main']['App']['ReturnBaseURL']();
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}
