// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function AddVideoInQueue(arg1:dto.Video):Promise<void>;

export function ConnectWSRoom(arg1:string):Promise<dto.State>;

export function CreateRoom():Promise<string>;

export function DeleteVideoInQueue(arg1:number):Promise<void>;

export function GetListVideo(arg1:string):Promise<Array<dto.Video>>;

export function ListenState():Promise<void>;

export function Next():Promise<void>;

export function PlayAndPause():Promise<void>;

export function ReturnBaseURL():Promise<string>;

export function Seek(arg1:number):Promise<void>;
